---

- name: Create OpenCV folder
  file:
    path: "{{ opencv_home }}"
    state: directory

- name: Install "OpenCV" node.js package.
  command: npm install --save opencv4nodejs@{{ opencv_version }} --prefix {{ opencv_home }} --unsafe-perm true

- name: Archive opencv packages
  shell: tar -czvf opencv.tar.gz {{ opencv_home }}

