---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package.
  command: npm install appium@{{ appium_version }} --prefix {{ appium_install_location }} --unsafe-perm true

# hotfix for screenrecord pidof functionality
- name: override appium-adb/build/lib/tools/adb-commands.js file
  copy: src="roles/appium/templates/adb-commands.js" dest={{ appium_install_location }}/node_modules/appium/node_modules/appium-adb/build/lib/tools/adb-commands.js

# exclude AppiumDriver.getStatus() call and response from debug log level
- name: override appium-base-driver/build/lib/protocol/protocol.js file
  copy: src="roles/appium/templates/protocol.js" dest={{ appium_install_location }}/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js

- name: Archive MCloud data
  shell: tar -czvf mcloud-appium.tar.gz /opt/mcloud

