---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package.
  command: npm install appium@{{ appium_version }} --prefix {{ appium_install_location }} --unsafe-perm true
